### ISSUE TITLE
ASX data issue

### ISSUE THREAD

**Issue by pomegranate-tonic** [chrisvenables/aus_share_trading_assistant#1]
Hi Chris!

The chatbot wasn't able to return my watchlist. I had a look at your readme and the problem appears to be with the ASX urls not working anymore, for example, I tried: http://data.asx.com.au/data/1/share/TLS and I was redirected to the homepage.

Cheers
James

**Comment by brendonwm** [comment]
FYI: https://www.asx.com.au/asx/1/share/TLS seems to work.

**Comment by pomegranate-tonic** [comment]
I see. Must have been down for a few days at the time. Thanks!

**Comment by brendonwm** [comment]
I think the ASX moved the URL.

**Comment by chrisvenables** [comment]
Thanks for the feedback and sorry it's taken me so long to respond! I've updated the data source to use the new ASX data URL. Should be working again now.

I also fixed up a new command which will give you that day's price trading range as well. You can invoke it by the command "What was today's price range for XXX?" where XXX is your stock code.

Please do raise issues if you have any other issues/questions/feedback.
